// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByHFyWts9LGyi5CzFwBOWarHHv3j6el3A',
    appId: '1:31707012186:web:e97a1d4eb9a7d623608c63',
    messagingSenderId: '31707012186',
    projectId: 'project2-f171a',
    authDomain: 'project2-f171a.firebaseapp.com',
    storageBucket: 'project2-f171a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcEmeVFVJD_g-VOZ51tqNDa17WuZ9rH3I',
    appId: '1:31707012186:android:62ab99e3b0858c7b608c63',
    messagingSenderId: '31707012186',
    projectId: 'project2-f171a',
    storageBucket: 'project2-f171a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8xn8XAxumi8KEf2_SygyXngZWFGuZdaU',
    appId: '1:31707012186:ios:91d7f0de41e4ef1d608c63',
    messagingSenderId: '31707012186',
    projectId: 'project2-f171a',
    storageBucket: 'project2-f171a.appspot.com',
    iosBundleId: 'com.example.projecttwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8xn8XAxumi8KEf2_SygyXngZWFGuZdaU',
    appId: '1:31707012186:ios:7c43c40486183120608c63',
    messagingSenderId: '31707012186',
    projectId: 'project2-f171a',
    storageBucket: 'project2-f171a.appspot.com',
    iosBundleId: 'com.example.projecttwo.RunnerTests',
  );
}
